name: Sync Fork

on:
  workflow_dispatch: # 允许手动触发
  schedule: # 定时触发，例如每天早上8点
    - cron: '0 8 * * *'
  push: # 当上游仓库有新的推送时触发
    branches:
      - master # 或master，取决于上游仓库的主分支名称


jobs:
  sync_fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }} # 你fork的仓库
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
          fetch-depth: 0 # 获取所有历史记录，这对于首次同步至关重要

      - name: Add upstream remote
        run: git remote add upstream https://github.com/zwc456baby/iptv_alive

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes into main branch
        run: |
          git checkout main
          git merge upstream/master --no-edit # 或master，取决于上游仓库的主分支名称

      - name: Push changes to your fork
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.PERSONAL_ACCESS_TOKEN  }}
          branch: master # 或master，取决于你fork的仓库的主分支名称
