name: Sync with Upstream

on:
  schedule:
    - cron: "0 8 * * *" # 每天8点执行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync with upstream repository
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: master # 您fork的仓库的分支名
          target_repo_token: ${{secrets.PERSONAL_ACCESS_TOKEN }} # 使用GitHub提供的访问令牌
          upstream_sync_repo: 'zwc456baby/iptv_alive' # 上游仓库的路径，例如：'aormsby/Fork-Sync-With-Upstream-action'
          upstream_sync_branch: master # 上游仓库的分支名
          test_mode: false # 测试模式，设置为false以实际执行同步
